import sys
from pathlib import Path
from pptx import Presentation
from pptx.util import Inches, Pt

# Define slide titles and placeholder content
sections = [
    ("Abstract", "- Brief overview of the project"),
    ("Introduction", "- Background and motivation"),
    ("Literature Survey", "- Summarize 10 recent papers (last 3 years)"),
    ("Problem Statement", "- Define the problem being addressed"),
    ("Design", "- System architecture and components"),
    ("Proposed Methodology", "- Approach and techniques"),
    ("Datasets", "- Description of datasets used"),
    ("Implementation", "- Key implementation details"),
    ("Test Cases", "- Overview of test scenarios"),
    ("Results & Discussion", "- Findings and analysis"),
    ("Conclusion", "- Summary and future work"),
    ("References", "- List of cited works")
]

# Create a presentation
prs = Presentation()

# Title slide
title_slide_layout = prs.slide_layouts[0]
slide = prs.slides.add_slide(title_slide_layout)
title = slide.shapes.title
subtitle = slide.placeholders[1]
title.text = "Review-III Presentation"
subtitle.text = "Generated by AI Assistant"

# Add a slide for each section
bullet_slide_layout = prs.slide_layouts[1]
for title_text, bullet in sections:
    slide = prs.slides.add_slide(bullet_slide_layout)
    slide.shapes.title.text = title_text
    tf = slide.placeholders[1].text_frame
    tf.text = bullet

# Save the presentation
output_path = Path(__file__).parent / "Review-III.pptx"
prs.save(str(output_path))
print(f"Presentation saved to {output_path}")
